## Week 4 Exercise 4.2 Author: Rex Gayas Course & Section: DSC320-T301 Math for Data Science (2243-1) Date: 07 January 2024

### Calculating Limits Numerically

In [52]:
#Solution to (a)

import numpy as np

def f(x):
    return 2*x**3 - 4*x + 1

def calculate_limit_approaching_x(func, target_x, delta):
    # Values approaching target_x from left and right
    values_left = np.arange(target_x - delta, target_x, delta / 10)
    values_right = np.arange(target_x, target_x + delta, delta / 10)

    # Evaluating the function for these values
    results_left = [func(x) for x in values_left]
    results_right = [func(x) for x in values_right]

    return values_left, results_left, values_right, results_right

# Calculate the limit of f(x) as x approaches 3
target_x = 3
delta = 0.1
values_left, results_left, values_right, results_right = calculate_limit_approaching_x(f, target_x, delta)

(values_left, results_left, values_right, results_right)


(array([2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96, 2.97, 2.98, 2.99, 3.  ]),
 [38.178,
  38.64434199999999,
  39.11417599999997,
  39.58751399999996,
  40.06436799999995,
  40.544749999999944,
  41.02867199999993,
  41.51614599999992,
  42.00718399999991,
  42.5017979999999,
  42.999999999999886],
 array([3.  , 3.01, 3.02, 3.03, 3.04, 3.05, 3.06, 3.07, 3.08, 3.09, 3.1 ]),
 [43.0,
  43.50180199999999,
  44.00721599999998,
  44.51625399999997,
  45.02892799999996,
  45.545249999999946,
  46.06523199999993,
  46.588885999999924,
  47.11622399999991,
  47.6472579999999,
  48.18199999999989])

As x approaches 3 from both sides, the value of f(x) approaches 43 which suggests that the limit of f(x) as x approaches 3 is 43. 

In [53]:
# Solution to (b)

def g(x):
    # Consideration of undefined value when x is 0 to avoid division by zero
    if x == 0:
        return float('inf')
    return (np.exp(x) - 1) / x

# Calculate the limit of g(x) as x approaches 0
target_x = 0
values_left, results_left, values_right, results_right = calculate_limit_approaching_x(g, target_x, delta)

(values_left, results_left, values_right, results_right)


(array([-0.1 , -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02,
        -0.01]),
 [0.9516258196404048,
  0.9563201636530201,
  0.9610456701670529,
  0.9658025727721689,
  0.9705911069291876,
  0.9754115099857191,
  0.9802640211919197,
  0.9851488817163935,
  0.9900663346622351,
  0.9950166250831954],
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]),
 [inf,
  1.005016708416795,
  1.0100670013377888,
  1.015151131783898,
  1.0202693548097053,
  1.0254219275204823,
  1.0306091090893275,
  1.0358311607745219,
  1.0410883459369829,
  1.0463809300578935])

As x approaches 0 from both sides, the value of g(x) approaches 1 which suggests that the limit of g(x) as x approaches 0 is 1.

#### Solution to (c)
For the polynomial function in (a), it is continues in all values as per definition. This allows directly plugging in the value of x where the limit is taken. Plugging in x = 3 for f(x) will result in 43 which is the same as the determined limit.
For the function in (b), Directly plugging in x = 0 leads to an undefined expression which implies that g(x) has a removable discontinuity at x = 0. 

### Average Rate of Change

In [54]:
def average_rate_of_change(f, a, b):
    """
    Calculate the average rate of change of the function f between points a and b.

    :param f: A function to calculate the average rate of change for.
    :param a: The starting point of the interval.
    :param b: The ending point of the interval.
    :return: The average rate of change of f from a to b.
    """
    # Check a and b are not the same to avoid division by zero
    if a == b:
        return float('inf')

    return (f(b) - f(a)) / (b - a)

# Sample function as provided in assignment
def example_function(x):
    return 3*x**2 

# Calculate the average rate of change for the example function between 1 and 2
arc_example = average_rate_of_change(example_function, 1, 2)
arc_example


9.0

The average rate of change of f(x) between the points 1 and 2 is 9.0 

### Average Rate of Change to Instantaneous Rate of Change

In [55]:
# Solution for (a)

# Define the function f(t) = 4.9t^2 for the baseball's distance
def baseball_distance(t):
    return 4.9 * t**2

# Average rate of change between 5 and 6 seconds 
arc_5_to_6 = average_rate_of_change(baseball_distance, 5, 6)

arc_5_to_6



53.89999999999999

In [56]:
# Solution for (b)

# Average rate of change between 5 and 5.5 seconds 
arc_5_to_5_5 = average_rate_of_change(baseball_distance, 5, 5.5)

arc_5_to_5_5


51.45000000000002

In [57]:
# Solution for (c)

# Average rate of change between 5 and 5.1 seconds 
arc_5_to_5_1 = average_rate_of_change(baseball_distance, 5, 5.1)

arc_5_to_5_1


49.490000000000016

In [58]:
# Solution for (d)

# Average rate of change between 5 and 5.05 seconds 
arc_5_to_5_05 = average_rate_of_change(baseball_distance, 5, 5.05)



# Average rate of change between 5 and 5.05 seconds 
arc_5_to_5_025 = average_rate_of_change(baseball_distance, 5, 5.025)

(arc_5_to_5_05, arc_5_to_5_025)


(49.24499999999984, 49.12249999999959)

As the difference of the initial and final t's decreases, the average rate of change is approaching 49.0

#### Solution for (e)

The derivative of f(t) = 4.9t^2 is f'(t) = 9.8t.

In [59]:
# Solution for (f)

# Instantaneous speed at t = 5 seconds (Part d), using the derivative f'(t) = 9.8t
instantaneous_speed_t_5 = instantaneous_rate_of_change_f(5)

instantaneous_speed_t_5


49.0

This is the same as the value for (d) and this equality aligns with the theoretical expectation for the instantaneous rate of change at t=5 seconds. Hence, this shows the concept of a derivative as the limit of the average rate of change as the interval approaches zero.

### Calculating and Interpreting Partial Derivatives

In [60]:
# Constants for the linear model
base_price = 16000
condition_coefficient = 2400
age_coefficient = -1800

# Solution for (a)
# Predicted selling price for a 5-year old car with a condition rating of 8
condition_rating = 8
car_age = 5

predicted_price = base_price + condition_coefficient * condition_rating + age_coefficient * car_age

print(predicted_price)

26200


In [61]:
# Solution for (b)

# Calculating the partial derivatives vis condition
partial_derivative_condition = condition_coefficient
 
print(partial_derivative_condition)


2400


This value indicates the rate of change of the selling price with respect to the condition rating. For each unit increase in the condition rating, the selling price increases by $2,400, keeping the car's age constant.

In [62]:
# Solution for (c)

# Calculating the partial derivatives vis age
partial_derivative_age = age_coefficient

print(partial_derivative_age)


-1800


This value signifies the rate of change of the selling price with respect to the car's age. For each additional year in the age of the car, the selling price decreases by $1,800, keeping the car's condition rating constant.